### ISSUE TITLE
Forgot Password has some internal server error

### ISSUE THREAD

**Issue by VishwanthSetty** [Nocturnals/ASE-3#37]
**Describe the bug**
When trying to request for forgot password from postman Internal error is showing up.

![image](https://user-images.githubusercontent.com/30575052/78875100-fee89980-7a6a-11ea-8ef5-55c07055125a.png)

**Comment by Hemanth759** [comment]
Everything working fine for me. Can you check again but this time with pulling the branch @VishwanthSetty

**Comment by Hemanth759** [comment]
I think @VishwanthSetty should also check the console as it prints the error if any

**Comment by VishwanthSetty** [comment]
kk i will check it again
