### ISSUE TITLE
Many errors in the post folder and getuserbyid and getuserbyusername functions

### ISSUE THREAD

**Issue by Hemanth759** [Nocturnals/ASE-3#38]
**Description of bug**
Many errors are found in the backend branch of the post folder when viewed from ts-check feature

**To Reproduce**
1. Go to '`backend` branch of the repository'
2. Click on 'post folder and view the files in vscode with tsscript extension enabled'
3. Scroll down to 'all the files in post folder and few files in auth folder'

![image](https://user-images.githubusercontent.com/33123731/79017179-57fd1e00-7b8e-11ea-8747-609381a66428.png)

**Comment by sriram012** [comment]
Resloved.

**Comment by Hemanth759** [comment]
Still some errors are present in 
`auth\helper.js`
`post\deleteAllPostOfLoggedUser.js`
`post\index.js`
`post\removeLike.js`

**Comment by sriram012** [comment]
Now everything is clear

**Comment by sriram012** [comment]
Pull now

**Comment by Hemanth759** [comment]
great now @sriram012  create a pull request to master branch and I will approve it
