### ISSUE TITLE
Error when sending post/get request to node

### ISSUE THREAD

**Issue by sriram012** [Nocturnals/ASE-3#47]
![image](https://user-images.githubusercontent.com/44209768/79332013-b54ff100-7f39-11ea-8c48-14b797a268a1.png)

**Comment by Hemanth759** [comment]
Which branch are you working on?

**Comment by sriram012** [comment]
Backend

**Comment by Hemanth759** [comment]
For me its working properly
![image](https://user-images.githubusercontent.com/33123731/79462364-02ed5c00-8015-11ea-9a4b-a8c143c20fa1.png)

**Comment by Hemanth759** [comment]
> Backend

once try by pulling

**Comment by Hemanth759** [comment]
Did you replace the firebase json file in backend with the new one in the discord?

**Comment by sriram012** [comment]
Will try and get back to you.

**Comment by sriram012** [comment]
It is working now. Thank you

**Comment by Hemanth759** [comment]
Glad to be helpful 😊
