### ISSUE TITLE
Failed host lookup: 'petsoc.azurewebsites.net'

### ISSUE THREAD

**Issue by sriram012** [Nocturnals/ASE-3#53]
![image](https://user-images.githubusercontent.com/44209768/81960079-07199300-962e-11ea-8b03-bbbc007e4b81.png)

**Comment by Hemanth759** [comment]
It's **working** for me.
Can you show the http.get request code?

**Comment by sriram012** [comment]
![image](https://user-images.githubusercontent.com/44209768/82012242-f94b2880-9694-11ea-8fe7-caf030650d8b.png)

**Comment by Hemanth759** [comment]
Localhost value?

**Comment by sriram012** [comment]
![image](https://user-images.githubusercontent.com/44209768/82014254-da02ca00-9699-11ea-909a-9bbeb78f66f6.png)

**Comment by Hemanth759** [comment]
Once head to that website in the browser and see if the site is working.
Try https://.....net/testing url that should give you current time

**Comment by sriram012** [comment]
![image](https://user-images.githubusercontent.com/44209768/82015163-bccefb00-969b-11ea-9d41-df447531b53f.png)
![image](https://user-images.githubusercontent.com/44209768/82015198-d3755200-969b-11ea-8740-638c62fea079.png)

**Comment by Hemanth759** [comment]
Yes that should work then. 
The url used in https://github.com/Nocturnals/ASE-3/issues/53#issuecomment-629022936 is not defined in the master branch of our application yet. Azure is only deployed when the master branch is changed and only reflects the master branch of our repo.

**Comment by sriram012** [comment]
Same error is repeating even after merging backend with master
![image](https://user-images.githubusercontent.com/44209768/82026412-57d1d000-96b0-11ea-8b02-777265ba4364.png)

**Comment by Hemanth759** [comment]
The changes you have made has errors in the model and hence shows many errors and the request is showing internal server error

**Comment by Hemanth759** [comment]
I have reverted the pull request to its previous commit. Please ensure the editted code works before creating pull request. And also we should create test cases so that we can see that the code works fine. # @NikhilMunna please create the test cases for auth module
